version: '3.8'

networks:
  kong-net:
    external: false

volumes:
  kong_data: {}

services:
  kong-database:
    image: postgres:9.6
    container_name: kong-database
    environment:
      POSTGRES_DB: kong
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: kong
    ports:
      - "5432:5432"
    volumes:
      - kong_data:/var/lib/postgresql/data
    networks:
      - kong-net
    
  kong-migration:
    image: kong:2.8
    container_name: kong-migration
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
    networks:
      - kong-net
    depends_on:
      - kong-database
    command: kong migrations bootstrap
  
  kong:
    image: kong:2.8
    container_name: kong
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
      KONG_PROXY_LISTEN: 0.0.0.0:8000, 0.0.0.0:9080 http2, 0.0.0.0:9081 http2 ssl
      KONG_ADMIN_GUI_LISTEN: 0.0.0.0:8002
    networks:
      - kong-net
    depends_on:
      - kong-database
      - kong-migration
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
      - "9080:9080"
      - "9081:9081"
      - "8002:8002"
  
  konga-prepare:
    image: pantsel/konga:latest
    container_name: konga-prepare
    environment:
      DB_ADAPTER: postgres
      DB_URI: postgres://kong:kong@kong-database:5432/konga
    networks:
      - kong-net
    depends_on:
      - kong-database
    command: -c prepare -a postgres -u postgresql://kong:kong@kong-database:5432/konga
  
  konga:
    image: pantsel/konga:latest
    container_name: konga
    environment:
      DB_ADAPTER: postgres
      DB_URI: postgres://kong:kong@kong-database:5432/konga
      KONGA_HOOK_TIMEOUT: 120000
      NODE_ENV: production
    networks:
      - kong-net
    depends_on:
      - kong-database
      - konga-prepare
    ports:
      - "1337:1337"